import { default as HeadNext } from 'next/head'

const Head = () => {

  return (
    <HeadNext>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </HeadNext>
  )
}

export default Head