import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const About: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <ul>
          <li>
            <Link href='/'>
              Homepage
            </Link>
          </li>
          <li>
            <Link href='/login'>
              Login
            </Link>
          </li>
          <li>
            <Link href='/about'>
              About
            </Link>
          </li>
        </ul>
      </header>
      <main>
        <h1>About Page</h1>
      </main>
    </>
  )
}

export default About