import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { getEntries } from './api/contentful'

type Options_type = {
  getType: 'content_type'
  getValue: string
  additionalOptions?: unknown
}

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <ul>
          <li>
            <Link href='/'>
              Homepage
            </Link>
          </li>
          <li>
            <Link href='/login'>
              Login
            </Link>
          </li>
          <li>
            <Link href='/about'>
              About
            </Link>
          </li>
        </ul>
      </header>
      <main>
        <h1>Home Page</h1>
      </main>
    </>
  )
}

export async function getStaticProps() {
  const page = await getEntries({
    getType: 'content_type',
    getValue: 'pageHome'
  })

  console.log(JSON.stringify(page))

  return {
    props:{
      page: JSON.stringify(page)
    }
  }
}

export default Home
