import { useQuery } from '@apollo/client';
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from  'next/link'
import { GET_PAGE_HOME } from '../queries/pageHome'

const Home: NextPage = () => {
  const { loading, error, data } = useQuery(GET_PAGE_HOME);

  console.log({
    loading,
    error,
    data
  })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <ul>
          <li>
            <Link href='/'>
              Homepage
            </Link>
          </li>
          <li>
            <Link href='/login'>
              Login
            </Link>
          </li>
          <li>
            <Link href='/about'>
              About
            </Link>
          </li>
        </ul>
      </header>
      <main>
        <h1>Home Page</h1>
      </main>
    </>
  )
}

// export const getStaticProps = async () => {
  
// }

export default Home
