import { useQuery } from '@apollo/client';
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from  'next/link'
import { GET_PAGE_HOME } from '../queries/pageHome'

type Options_type = {
  getType: 'content_type'
  getValue: string
  additionalOptions?: unknown
}

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <ul>
          <li>
            <Link href='/'>
              Homepage
            </Link>
          </li>
          <li>
            <Link href='/login'>
              Login
            </Link>
          </li>
          <li>
            <Link href='/about'>
              About
            </Link>
          </li>
        </ul>
      </header>
      <main>
        <h1>Home Page</h1>
      </main>
    </>
  )
}

// export const getStaticProps = async ({ apolloClient }: any) => {
//   const { data, loading, error } = await apolloClient.query({
//     query: GET_PAGE_HOME,
//   });

//   console.log({
//     loading,
//     error,
//     data
//   })

//   return {
//     loading,
//     error,
//     data
//   }
// }

export const getStaticProps = async (test) => {

  console.log(test)

  return {
    props: {
      test: true
    }
  }
}

export default Home