create table "public"."Test Table!" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now()
);


alter table "public"."Test Table!" enable row level security;

CREATE UNIQUE INDEX "Test Table!_pkey" ON public."Test Table!" USING btree (id);

alter table "public"."Test Table!" add constraint "Test Table!_pkey" PRIMARY KEY using index "Test Table!_pkey";


